# Generated by Django 4.2.6 on 2023-12-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuito',
            name='numCircuito',
            field=models.IntegerField(default=0, verbose_name='No. Circuitos'),
        ),
        migrations.AddField(
            model_name='distrito',
            name='numDistrito',
            field=models.IntegerField(default=0, verbose_name='No. Distritos'),
        ),
        migrations.AddField(
            model_name='subciruito',
            name='numSubCircuito',
            field=models.IntegerField(default=0, verbose_name='No. SubCircuitos'),
        ),
    ]
