# Generated by Django 4.2.6 on 2023-12-24 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gasolinera_tipocombustible_ordencombustible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipocombustible',
            options={'ordering': ['nombre'], 'verbose_name': 'Tipo de Combustible', 'verbose_name_plural': 'Tipos de Combustible'},
        ),
        migrations.AlterField(
            model_name='ordencombustible',
            name='idTipoCombustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipocombustible', verbose_name='Tipo de Combustible'),
        ),
    ]
