# Generated by Django 4.2.6 on 2023-12-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tipocombustible_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despachocombustible',
            name='fechaOrden',
            field=models.DateField(verbose_name='Fecha de Despacho'),
        ),
        migrations.AlterField(
            model_name='despachocombustible',
            name='idOrdenCombustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ordencombustible', verbose_name='Orden de Combustible'),
        ),
        migrations.AlterField(
            model_name='ordencombustible',
            name='horaLlegada',
            field=models.TimeField(verbose_name='Hora de Llegada'),
        ),
    ]
