# Generated by Django 4.2.6 on 2023-12-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_despachocombustible_fechaorden_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencombustible',
            options={'ordering': ['idOrdenCombustible'], 'verbose_name': 'Orden de Combustible', 'verbose_name_plural': 'Ordenes de Combustible'},
        ),
    ]
