# Generated by Django 4.2.6 on 2023-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_ordencombustible_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencombustible',
            options={'ordering': ['fechaSolicitud'], 'verbose_name': 'Orden de Combustible', 'verbose_name_plural': 'Ordenes de Combustible'},
        ),
        migrations.AlterField(
            model_name='despachocombustible',
            name='fechaOrden',
            field=models.DateTimeField(verbose_name='Fecha de Despacho'),
        ),
    ]
