# Generated by Django 4.2.6 on 2024-01-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_solicitudmovilizacion_ordenmovilizacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudmovilizacion',
            old_name='Ruta',
            new_name='ruta',
        ),
    ]
