# Generated by Django 4.2.6 on 2024-01-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_ruta_solicitudmovilizacion_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudmovilizacion',
            name='fechaSalida',
            field=models.DateField(verbose_name='Fecha de Salida'),
        ),
        migrations.AlterField(
            model_name='solicitudmovilizacion',
            name='fechaSolicitud',
            field=models.DateField(verbose_name='Fecha de Solicitud'),
        ),
    ]
