# Generated by Django 4.2.6 on 2024-01-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ordenmovilizacion_idestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenmovilizacion',
            name='fechaSolicitud',
            field=models.DateField(verbose_name='Fecha de Solicitud'),
        ),
    ]
