# Generated by Django 4.2.6 on 2024-01-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_ordenmovilizacion_idsolicitudmovilizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='idCanton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.canton', verbose_name='Cantón'),
        ),
    ]
